### ISSUE TITLE
DTX to PS: Blue cymbals being charted as yellow cymbals in pro drums

### ISSUE THREAD

**Issue by GabrielAC2019** [mtolly/onyxite-customs#133]
When importing dtx files to convert to phase shift midi, notes that should be blue cymbals (the leftmost cymbal in dtx charts) are being charted as yellow cymbals. Additionally, notes that should be charted as yellow cymbals (the second-to-leftmost cymbal in dtx charts) do work properly and are still charted as yellow cymbals. Basically, there is no differentiation between the two cymbals and they are charted to the same note.

**Comment by mtolly** [comment]
Hi @GabrielAC2019 , sorry for the delay in responding. I'm happy someone else is interested in converting DTX files!

Yeah, you're absolutely right that the left crash and hihat both being yellow next to each other is not good. However I don't think it should always be blue either -- for example double crashes are usually written Y+G in RB; and also in sections using ride cymbal and left crash, since the ride is also blue, left crash makes sense on yellow. I think the right answer is that it needs to look at what cymbals are before/after it in time (not just at the same time like it does now), and pick blue or yellow to contrast appropriately. I'll see if I can implement that soon.

Another factor is that Phase Shift has its "Real Drums" mode, which I do intend on exporting eventually, and that distinguishes between yellow hihat notes (open, closed, or pedal-close) and yellow crash notes. But even there you're right it probably makes sense to use blue when next to hihats.

**Comment by GabrielAC2019** [comment]
@

**Comment by GabrielAC2019** [comment]
Thanks for the response. I’m looking forward to the drums real export for dtx charts. I believe for dtx charts, all cymbals should be differentiated so it can remain as true to the original as possible. I think having an option to either have left crash on yellow or left crash on blue would be good enough in this case.
