### ISSUE TITLE
Error when creating Magma projects

### ISSUE THREAD

**Issue by JohnSmith2007** [mtolly/onyxite-customs#137]
ERROR! <stdout>: commitBuffer: invalid argument (invalid character)
I have no clue of what this means. What is it and how do I fix it?

**Comment by mtolly** [comment]
Hi @JohnSmith2007 , yes, this sounds like an error on my part, probably because it's trying to write a special character in a file that doesn't support it.
Can you post a link to the song file you're converting from, so I can test?

**Comment by JohnSmith2007** [comment]
[Rhett Nelson - Power Rangers Jungle Fury Theme.zip](https://github.com/mtolly/onyxite-customs/files/4176444/Rhett.Nelson.-.Power.Rangers.Jungle.Fury.Theme.zip)

**Comment by mtolly** [comment]
Turns out it wasn't what I expected; the root cause is that your MIDI file has some unexpected data, and that caused it to try to print out a parse warning in a corrupted way. I'll fix that (the warning causing a crash) in the next version. Here is a replacement file you can drop in:

[notes.zip](https://github.com/mtolly/onyxite-customs/files/4223150/notes.zip)

If you don't mind me asking, what program did you use to create that MIDI file?

**Comment by JohnSmith2007** [comment]
I made it using Moonscraper Chart Editor, because using REAPER means placing down each note individually, making that really time consuming. Moonscraper, however, has a function called "Keys Mode", which allows me to place notes as the song plays, using the 1,2,3,4,& 5 keys. Vocals are still done on REAPER.

**Comment by JohnSmith2007** [comment]
Also, how did you fix it, and is it possible if you could tell me what programs you used to fix it, that way i can avoid these situations without needing to constantly annoy you each time? 
(Sorry if this sounds rude, I don't mean this in a rude way)

**Comment by mtolly** [comment]
I've put up a new version just now that should fix the specific issue going forward.

<https://github.com/mtolly/onyxite-customs/releases>
