### ISSUE TITLE
Bring back the automatic preview folder from previous versions

### ISSUE THREAD

**Issue by i0brendan0** [mtolly/onyxite-customs#158]
I liked that before the program got rewritten and changed completely, that when you made a preview, it always defaulted to <current folder name>_preview in the same folder. Now I have to go through every single folder to get to the one I just came from. I have a lot of folders in folders in folders.... At least make an option to default to the same folder you're in.

**Comment by mtolly** [comment]
I'm not sure what you mean by not defaulting to _preview in the same folder, are you talking about the preview tab in the Batch mode, or in the single-song view? In both cases it should be defaulting to making "whatever_preview" next to the song file. Can you explain what it's doing instead?

In the new version `20201121` I also added an option in `Edit > Preferences` to set a single folder where all previews will go by default, if that would make more sense.

**Comment by i0brendan0** [comment]
Earlier before the program was changed completely and only had 3 or 4 option, the program would automatically place the preview folder alongside the custom or phase shift folder you picked for the preview. Now when you select “web preview” it’ll ask you where you want to put the files. The old way is much better. Like if I had converted to phase shift and made a preview that way, it would create a <folder name>_preview folder in the same folder the phase shift conversion went. Now it asks for a folder and just puts the files in that folder, not in its own folder either.

**Comment by mtolly** [comment]
Ahh, I finally understand the issue here. I didn't realize how useless the "Save to Folder" dialog I'm using was on Windows, and that it is doing the unhelpful behavior you describe. On Linux which I usually am developing on it is more like the normal Save File dialog that works exactly like you were expecting. I have fixed this to use the better dialog and I am hoping to do a release tomorrow that should work better. Sorry for the delay in fixing this!

**Comment by mtolly** [comment]
Release `20210110` should have this fixed, let me know if it is still not behaving as expected.
