### ISSUE TITLE
Antivirus flags AppData Local Temp Magma when compiling Rock Band Songs

### ISSUE THREAD

**Issue by SquirmyElk2** [mtolly/onyxite-customs#243]
My antivirus (Emsisoft Anti-Malware) is warning me about the Magma folder every time I compile a Rock Band song with this toolkit. I cannot make an exception in the antivirus because Onyx places a Magma folder in C:\Users\(User)\AppData\Local\Temp and deletes it after executing. I often convert Phase Shift songs to RB3 format in bulk and it gets annoying after multiple instances of telling the antivirus that Magma is a safe program. The only solutions to the problem is to shut off the antivirus or make an exception in the Temp folder and I am not willing to do those things.

Is there any way to make Onyx execute Magma straight from (Chosen Install Directory)\OnyxToolkit\onyx-resources\magma-v2 folder instead of C:\Users\(User)\AppData\Local\Temp when converting songs to Rock Band 2/3 Formats?

**Comment by mtolly** [comment]
Hm, yeah that's a tricky problem. In the future I plan to improve how Magma is used and can probably remove the need to assemble the program files elsewhere. One workaround you can do for now is to simply disable Magma, from `Edit > Preferences > Rock Band` - this will skip the final MIDI check + camera/lights generation, but otherwise should generally work - hope that is helpful.
