### ISSUE TITLE
Import a 1x and 2x bass pedal version together

### ISSUE THREAD

**Issue by mtolly** [mtolly/onyxite-customs#65]
Should import into the Phase Shift 2x format (with left kicks on 95), and probably just error out if the 2x version isn't a perfect superset of 1x.

**Comment by mtolly** [comment]
This is already supported for FoF/PS import (from `expert+.mid`). Also, we now support PART DRUMS_2X so the perfect subset requirement is removed.

**Comment by TheT113** [comment]
Hey there, sorry to bump an extremely old (and closed) post, and hopefully you do somehow see this, but: how do you actually do this, import them together? I have cons that I want to combine the 2x bass to Expert+, but it seems like Onyx is instead reducing them itself rather than importing the 1x? Is there a trick to how I'm supposed to be loading it?
